// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJsXlHh7MgPGJ4Nice2K6cLfHdMrNoq7s',
    appId: '1:303335506080:web:d2eddc2b047e60f39549c5',
    messagingSenderId: '303335506080',
    projectId: 'iw-nexus',
    authDomain: 'iw-nexus.firebaseapp.com',
    storageBucket: 'iw-nexus.firebasestorage.app',
    measurementId: 'G-PFS81W5ES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoLhzZdeUJrHbQq-dvYLKpMjerlv65LZk',
    appId: '1:303335506080:android:b85c055da85b61db9549c5',
    messagingSenderId: '303335506080',
    projectId: 'iw-nexus',
    storageBucket: 'iw-nexus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiNeIZ79DsML0gE6RBxAMzkAZ0IUNZ_iI',
    appId: '1:303335506080:ios:be83bebdbc64d0099549c5',
    messagingSenderId: '303335506080',
    projectId: 'iw-nexus',
    storageBucket: 'iw-nexus.firebasestorage.app',
    iosBundleId: 'com.iwn.iwNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiNeIZ79DsML0gE6RBxAMzkAZ0IUNZ_iI',
    appId: '1:303335506080:ios:be83bebdbc64d0099549c5',
    messagingSenderId: '303335506080',
    projectId: 'iw-nexus',
    storageBucket: 'iw-nexus.firebasestorage.app',
    iosBundleId: 'com.iwn.iwNexus',
  );
}